name: auto-test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir build
        working-directory: src/
      - run: cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_CXX_COMPILER:FILEPATH=$(which clang++) -S . -B build -G "Unix Makefiles"
        working-directory: src/
      - run: make
        working-directory: src/build/
